### ISSUE TITLE
Maintain usher_barcodes.csv for those who haven't updated to 1.5.1

### ISSUE THREAD

**Issue by arianna-smith** [andersen-lab/Freyja-data#3]
Would it be possible for `usher_barcodes.csv` to be updated along with `usher_barcodes.feather` for the time being? We hardcode our freyja version in our workflows and were unaware that we needed to update to 1.5.1 to continue having the most up-to-date barcodes, so our data has technically been out of date since June. We are updating to 1.5.1, but I assume there are others in the same situation.

**Comment by joshuailevy** [comment]
Hey Arianna - using our original set up, the csvs got too big (>100MB) for normal storage on github. I can make them available using LFS though, if that works for you?

**Comment by joshuailevy** [comment]
Should be solved by this commit: https://github.com/andersen-lab/Freyja-data/commit/4a3062f27302d1be84293a1dd32c855254202259. Let me know if that doesn't solve the problem!
